chore: fix retry cp file to oss

diff --git a/.github/workflows/save-images-arm64.yml b/.github/workflows/save-images-arm64.yml
--- a/.github/workflows/save-images-arm64.yml
+++ b/.github/workflows/save-images-arm64.yml
@@ -148,8 +148,25 @@ jobs:
           IMAGE_PKG_NAME="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz"
           IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
           mv ${IMAGE_PKG_NAME} ${IMAGE_PKG_NAME_ARM64}
-          ossutil cp -rf ./${IMAGE_PKG_NAME_ARM64} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64}
-          upload_ret=$?
+          
+          upload_ret=0
+          for i in {1..10}; do
+              echo "ossutil cp ${IMAGE_PKG_NAME_ARM64} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64} ..."
+              ossutil cp -rf ./${IMAGE_PKG_NAME_ARM64} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64}  --read-timeout=420 --retry-times=5
+              upload_ret=$?
+          
+              ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)" 
+              if [[ -f "${ossutil_report_file_name}" ]]; then
+                  echo "cp ${IMAGE_PKG_NAME_ARM64} to oss error, retry..."
+                  cat "${ossutil_report_file_name}"
+                  rm -rf ossutil_output/ossutil_report_*.report
+                  upload_ret=1
+              elif [[ $upload_ret -eq 0 ]]; then
+                  break
+              fi
+              sleep 1
+          done
+          
           if [[ $upload_ret -eq 0 ]]; then
               echo "upload ${IMAGE_PKG_NAME_ARM64} to oss successfully"
           else
